const ROUTINE={morning:{title:'🌅 Mañana',items:[['🐶','Sacar a los perros al baño y darles de comer','07:00','07:20'],['🍳','Desayunar','07:20','07:50'],['🍽️','Lavar los trastes','07:50','08:30'],['🪴','Regar las plantas','08:30','08:45'],['🧹','Lavar/limpiar el patio de los perros','08:45','09:20'],['🛏️','Hacer la cama','09:20','09:30'],['👕','Meter la ropa a la lavadora','09:30','09:35'],['🚿','Bañarme y arreglarme','09:35','10:05'],['💻','Publicidad / programación','10:05','11:00'],['🚗','Prepararme para salir, compras de despensa y salir a trabajar','11:00','12:00']]},work:{title:'🏢 Trabajo',items:[['🏢','Trabajo / compras / actividades externas','12:00','16:00']]},afternoon:{title:'🌆 Tarde',items:[['🏠','Llegar a casa y comer','16:00','16:30'],['🐶','Dar de comer a los perros','16:30','16:45'],['😌','Descansar','16:45','17:15'],['💻','Publicidad / programación','17:15','18:30'],['🧹','Pendientes de casa','18:30','19:00'],['🍽️','Cena','19:00','19:45'],['🐕','Pasear a los perros','19:45','20:15']]},night:{title:'🌙 Noche',items:[['🚿','Bañarme por la noche si lo necesito','20:15','20:45'],['📺','Ver televisión y relajarme','20:45','21:45'],['📋','Organizar el día siguiente y revisar pendientes','21:45','22:15'],['😌','Desconexión y preparación para dormir','22:15','23:00'],['😴','Hora objetivo para dormir','23:00','23:01']]}};
const ORDER=['morning','work','afternoon','night'];
const $=id=>document.getElementById(id);
const els={date:$('currentDate'),day:$('currentDay'),clock:$('clock'),percent:$('progressPercent'),fill:$('progressFill'),done:$('completedCount'),total:$('totalCount'),currentCard:$('currentActivityCard'),currentTime:$('currentActivityTime'),currentName:$('currentActivityName'),currentEmoji:$('currentActivityEmoji'),remaining:$('timeRemaining'),free:$('freeTimeCard'),nextCard:$('nextActivityCard'),nextTime:$('nextActivityTime'),nextName:$('nextActivityName'),nextEmoji:$('nextActivityEmoji'),container:$('activitiesContainer'),infoDone:$('infoCompleted'),infoTotal:$('infoTotal'),infoProgress:$('infoProgress'),infoNext:$('infoNext')};
const todayKey=()=>`rutina_${new Date().toLocaleDateString('sv-SE')}`;
const toMinutes=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};
const pad=n=>String(n).padStart(2,'0');
const duration=n=>n<60?`${n} min`:`${Math.floor(n/60)} h${n%60?` ${n%60} min`:''}`;
const flat=()=>ORDER.flatMap(section=>ROUTINE[section].items.map((x,i)=>({emoji:x[0],name:x[1],start:x[2],end:x[3],section,localIndex:i})));
const read=()=>JSON.parse(localStorage.getItem(todayKey())||'{}');
const write=data=>localStorage.setItem(todayKey(),JSON.stringify(data));
const nowMinutes=()=>{const d=new Date();return d.getHours()*60+d.getMinutes()};
const currentOf=(items,time)=>items.find(x=>time>=toMinutes(x.start)&&time<toMinutes(x.end))||null;
const nextOf=(items,time)=>items.filter(x=>toMinutes(x.start)>time).sort((a,b)=>toMinutes(a.start)-toMinutes(b.start))[0]||null;
function updateClock(){const d=new Date();els.clock.textContent=`${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;els.date.textContent=d.toLocaleDateString('es-ES',{day:'numeric',month:'long',year:'numeric'});els.day.textContent=d.toLocaleDateString('es-ES',{weekday:'long'});}
function render(){const items=flat(),state=read(),time=nowMinutes(),current=currentOf(items,time),next=nextOf(items,time),completed=items.reduce((n,_,i)=>n+(state[i]?1:0),0),percent=Math.round(completed/items.length*100);updateClock();els.percent.textContent=percent;els.fill.style.width=`${percent}%`;els.done.textContent=completed;els.total.textContent=items.length;els.infoDone.textContent=completed;els.infoTotal.textContent=items.length;els.infoProgress.textContent=percent;els.currentCard.hidden=!current;els.free.hidden=!!current;els.nextCard.hidden=!next;if(current){els.currentTime.textContent=`${current.start} — ${current.end}`;els.currentName.textContent=current.name;els.currentEmoji.textContent=current.emoji;els.remaining.textContent=`Faltan ${duration(Math.max(1,toMinutes(current.end)-time))}`;}if(next){els.nextTime.textContent=`${next.start} — ${next.end}`;els.nextName.textContent=next.name;els.nextEmoji.textContent=next.emoji;els.infoNext.textContent=`${next.start} — ${next.name}`;}else els.infoNext.textContent='—';els.container.innerHTML='';ORDER.forEach(sectionKey=>{const section=document.createElement('section');section.className='section';section.innerHTML=`<div class="section-title">${ROUTINE[sectionKey].title}</div>`;ROUTINE[sectionKey].items.forEach((item,localIndex)=>{const index=items.findIndex(x=>x.section===sectionKey&&x.localIndex===localIndex),done=!!state[index],isCurrent=current&&current.section===sectionKey&&current.localIndex===localIndex,past=time>=toMinutes(item[3])&&!isCurrent,card=document.createElement('article');card.className=`activity${done?' done':''}${isCurrent?' current':''}${past?' past':''}`;card.innerHTML=`<button class="toggle" type="button" aria-label="Marcar actividad">${done?'✓':'○'}</button><div class="activity-main"><h3 class="activity-title">${item[0]} ${item[1]}</h3><div class="activity-meta"><span class="pill">${item[2]} — ${item[3]}</span><span class="pill">⏱ ${duration(Math.max(0,toMinutes(item[3])-toMinutes(item[2])))}</span></div></div><div class="status">${done?'COMPLETADA':isCurrent?'ACTUAL':'PENDIENTE'}</div>`;card.querySelector('.toggle').addEventListener('click',()=>{const nextState=read();nextState[index]=!nextState[index];write(nextState);render();});section.appendChild(card);});els.container.appendChild(section);});}
$('resetBtn').addEventListener('click',()=>{if(confirm('¿Quieres reiniciar las actividades de hoy?')){localStorage.removeItem(todayKey());render();}});
render();setInterval(updateClock,1000);setInterval(render,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});
